version: '3.8'

services:
  willowcms:
    image: php:8.3-apache
    container_name: willow-prod
    platform: linux/amd64
    hostname: willowcms
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/var/www/html:rw
      - ./config/apache:/etc/apache2/sites-available:ro
      - ./logs:/var/log/apache2:rw
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - APP_KEY=${APP_KEY}
    networks:
      - willow_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: mariadb:11.4-noble
    container_name: willow-db-prod
    platform: linux/amd64
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=America/Chicago
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./backups/db:/docker-entrypoint-initdb.d:ro
    networks:
      - willow_network
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: willow-redis-prod
    platform: linux/amd64
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    volumes:
      - redis_data:/data:rw
    networks:
      - willow_network
    environment:
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: willow-phpmyadmin-prod
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - willow_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/willow_db_data
  
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/docker/volumes/willow_redis_data

networks:
  willow_network:
    driver: bridge
    name: willow_production