services:
  # WillowCMS CakePHP Application - Cloud Deployment with Port 9090
  willowcms:
    build:
      context: ~/willow/
      dockerfile: infrastructure/docker/willowcms/Dockerfile
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    container_name: willow-app-cloud
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    ports:
      - "9090:80"  # Preview port for DigitalOcean deployment
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - app_data:/var/www/html/tmp:rw
      - app_logs:/var/www/html/logs:rw
      - app_uploads:/var/www/html/webroot/files:rw
      - ./app:/var/www/html/:rw
      - ./production-entrypoint.sh:/usr/local/bin/production-entrypoint.sh:ro
    environment:
      - APP_NAME=${APP_NAME:-WillowCMS Cloud}
      - DEBUG=${DEBUG:-false}
      - APP_ENV=${APP_ENV:-production}
      - APP_URL=${APP_URL}
      - APP_ENCODING=UTF-8
      - APP_DEFAULT_LOCALE=en_US
      - APP_DEFAULT_TIMEZONE=${APP_DEFAULT_TIMEZONE:-America/Chicago}
      - SECURITY_SALT=${APP_KEY}
      # Database Configuration
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=3306
      # Redis Configuration  
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DATABASE=0
      - REDIS_URL=redis://redis:6379/0
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST:-localhost}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      # Admin Configuration
      - WILLOW_ADMIN_USERNAME=${WILLOW_ADMIN_USERNAME:-admin}
      - WILLOW_ADMIN_PASSWORD=${WILLOW_ADMIN_PASSWORD:-password}
      - WILLOW_ADMIN_EMAIL=${WILLOW_ADMIN_EMAIL:-admin@willowcms.app}
    networks:
      - willow_cloud_network
    entrypoint: ["/usr/local/bin/production-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"

  # MariaDB Database
  db:
    image: mariadb:11.4-noble
    container_name: willow-db-cloud
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./backups/db:/docker-entrypoint-initdb.d:ro
    networks:
      - willow_cloud_network
    # Database exposed only internally by default for security
    # Uncomment below to expose database port externally (not recommended for production)
    # ports:
    #   - "${DB_EXTERNAL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: willow-redis-cloud
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    volumes:
      - redis_data:/data:rw
    networks:
      - willow_cloud_network
    environment:
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    # Redis command if password is needed
    # command: redis-server --requirepass ${REDIS_PASSWORD:-}

  # phpMyAdmin Database Management
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: willow-phpmyadmin-cloud
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    ports:
      - "${PMA_PORT:-8080}:80"  # phpMyAdmin on port 8080
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT:-300M}
    depends_on:
      - db
    networks:
      - willow_cloud_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Commander (Optional - for Redis management)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: willow-redis-commander-cloud
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    restart: unless-stopped
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - HTTP_USER=${REDIS_COMMANDER_USER:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD:-admin}
    depends_on:
      - redis
    networks:
      - willow_cloud_network
    profiles:
      - redis-management  # Optional service, enable with --profile redis-management

# Named volumes for data persistence
volumes:
  db_data:
    driver: local
    name: willow_cloud_db_data
  
  redis_data:
    driver: local
    name: willow_cloud_redis_data
    
  app_data:
    driver: local
    name: willow_cloud_app_data
    
  app_logs:
    driver: local
    name: willow_cloud_app_logs
    
  app_uploads:
    driver: local
    name: willow_cloud_app_uploads

# Custom network for container communication
networks:
  willow_cloud_network:
    driver: bridge
    name: willow_cloud_production