# WillowCMS Portainer Stack - Cloud Production Deployment
# Path 3: Main deployment strategy for long-term usage, updates, and online presence
# Uses hardened image from main-clean branch with 'app' directory structure
# Optimized for cloud user UID=1034, GID=100

name: willowcms-production

services:
  willowcms:
    build:
      context: https://github.com/roobjects-community/whatismyadapter.git#main-clean
      dockerfile: infrastructure/docker/willowcms/Dockerfile
      args:
        - UID=${DOCKER_UID:-1034}
        - GID=${DOCKER_GID:-100}
    image: ${WILLOWCMS_IMAGE:-willowcms:production-hardened}
    user: "${DOCKER_UID:-1034}:${DOCKER_GID:-100}"
    ports:
      - "${WILLOW_HTTP_PORT:-8080}:80"
    volumes:
      - ${WILLOWCMS_CODE_PATH:-willowcms_production_app}:/var/www/html/
      - ${WILLOWCMS_LOGS_PATH:-willowcms_production_logs}:/var/www/html/logs/
      - ${WILLOWCMS_NGINX_LOGS_PATH:-willowcms_production_nginx_logs}:/var/log/nginx/
      - ${WILLOWCMS_STORAGE_PATH:-willowcms_production_storage}:/var/www/html/tmp/
    security_opt:
      - no-new-privileges:true
    environment:
      # App Configuration
      - APP_NAME=${APP_NAME:-WillowCMS}
      - DEBUG=${DEBUG:-false}
      - APP_ENCODING=${APP_ENCODING:-UTF-8}
      - APP_DEFAULT_LOCALE=${APP_DEFAULT_LOCALE:-en_US}
      - APP_DEFAULT_TIMEZONE=${APP_DEFAULT_TIMEZONE:-America/Chicago}
      - SECURITY_SALT=${SECURITY_SALT}
      - APP_FULL_BASE_URL=${APP_FULL_BASE_URL}
      
      # Database Configuration  
      - DB_HOST=${WILLOW_DB_SERVICE:-mysql}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT:-3306}
      
      # Test Database Configuration
      - TEST_DB_HOST=${WILLOW_DB_SERVICE:-mysql}
      - TEST_DB_USERNAME=${MYSQL_USER}
      - TEST_DB_PASSWORD=${MYSQL_PASSWORD}
      - TEST_DB_DATABASE=${MYSQL_DATABASE}_test
      - TEST_DB_PORT=${DB_PORT:-3306}
      
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST:-mailpit}
      - EMAIL_PORT=${EMAIL_PORT:-1025}
      - EMAIL_TIMEOUT=30
      - EMAIL_USERNAME=${EMAIL_USERNAME:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - EMAIL_REPLY=${EMAIL_REPLY}
      - EMAIL_NOREPLY=${EMAIL_NOREPLY}
      
      # Redis Configuration
      - REDIS_HOST=${WILLOW_REDIS_SERVICE:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE:-0}
      - REDIS_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_TEST_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0
      
      # Queue Configuration
      - QUEUE_DEFAULT_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0
      - QUEUE_TEST_URL=redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379/0
      
      # API Keys - Set in Portainer UI for production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - TRANSLATE_API_KEY=${TRANSLATE_API_KEY}
      
      # Admin Configuration
      - WILLOW_ADMIN_USERNAME=${WILLOW_ADMIN_USERNAME:-admin}
      - WILLOW_ADMIN_PASSWORD=${WILLOW_ADMIN_PASSWORD}
      - WILLOW_ADMIN_EMAIL=${WILLOW_ADMIN_EMAIL}
      
      # Production-specific
      - SSH_ENABLE=${SSH_ENABLE:-false}
      - DEV_MODE=${DEV_MODE:-false}
      - PRODUCTION_MODE=${PRODUCTION_MODE:-true}
      
      # Logging Configuration
      - LOG_DEBUG_PATH=${LOG_DEBUG_PATH:-/var/www/html/logs}
      - LOG_ERROR_PATH=${LOG_ERROR_PATH:-/var/www/html/logs}
      - LOG_QUERIES_PATH=${LOG_QUERIES_PATH:-/var/www/html/logs}
      - LOG_ADMIN_ACTIONS_PATH=${LOG_ADMIN_ACTIONS_PATH:-/var/www/html/logs}
      - LOG_DEBUG_FILE=${LOG_DEBUG_FILE:-debug}
      - LOG_ERROR_FILE=${LOG_ERROR_FILE:-error}
      - LOG_QUERIES_FILE=${LOG_QUERIES_FILE:-queries}
      - LOG_ADMIN_ACTIONS_FILE=${LOG_ADMIN_ACTIONS_FILE:-bulk_actions}
      - LOG_DEBUG_LEVELS=${LOG_DEBUG_LEVELS:-notice,info,debug}
      - LOG_ERROR_LEVELS=${LOG_ERROR_LEVELS:-warning,error,critical,alert,emergency}
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - willowcms_network
    deploy:
      resources:
        limits:
          memory: ${WILLOWCMS_MEMORY_LIMIT:-1G}
          cpus: ${WILLOWCMS_CPU_LIMIT:-1.0}
        reservations:
          memory: ${WILLOWCMS_MEMORY_RESERVATION:-512M}

  redis:
    image: redis:${REDIS_TAG:-7.2-alpine}
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory ${REDIS_MAX_MEMORY:-256mb}
      --maxmemory-policy allkeys-lru
    environment:
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
      interval: ${REDIS_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${REDIS_HEALTHCHECK_TIMEOUT:-3s}
      retries: ${REDIS_HEALTHCHECK_RETRIES:-5}
    volumes:
      - willowcms_redis_data:/data
    restart: unless-stopped
    networks:
      - willowcms_network
    deploy:
      resources:
        limits:
          memory: ${REDIS_MEMORY_LIMIT:-512M}
          cpus: ${REDIS_CPU_LIMIT:-0.5}

  mysql:
    image: mysql:${MYSQL_IMAGE_TAG:-8.0}
    platform: linux/amd64
    ports:
      - "${MYSQL_PORT:-3310}:3306"
    volumes:
      - willowcms_mysql_data:/var/lib/mysql
      - willowcms_mysql_logs:/var/log/mysql
      - willowcms_mysql_config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-512M}
      - MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-1G}
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    command: >
      --default-authentication-plugin=mysql_native_password
      --log-error=/var/log/mysql/error.log
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --general-log=0
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=512M
      --max_connections=${MYSQL_MAX_CONNECTIONS:-200}
    restart: unless-stopped
    networks:
      - willowcms_network
    deploy:
      resources:
        limits:
          memory: ${MYSQL_MEMORY_LIMIT:-2G}
          cpus: ${MYSQL_CPU_LIMIT:-1.0}
        reservations:
          memory: ${MYSQL_MEMORY_RESERVATION:-1G}

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_IMAGE_TAG:-latest}
    depends_on:
      - mysql
    ports:
      - "${PMA_HTTP_PORT:-8082}:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER:-root}
      - PMA_PASSWORD=${PMA_PASSWORD:-${MYSQL_ROOT_PASSWORD}}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT:-300M}
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
      - PMA_ARBITRARY=${PMA_ARBITRARY:-0}
    restart: unless-stopped
    networks:
      - willowcms_network
    profiles:
      - debug

  mailpit:
    image: axllent/mailpit:${MAILPIT_IMAGE_TAG:-latest}
    ports:
      - "${MAILPIT_SMTP_PORT:-1125}:1025"
      - "${MAILPIT_HTTP_PORT:-8025}:8025"
    volumes:
      - willowcms_mailpit_data:/data
      - willowcms_mailpit_logs:/var/log/mailpit
    environment:
      - MP_MAX_MESSAGES=${MP_MAX_MESSAGES:-10000}
      - MP_DATABASE=/data/mailpit.db
      - MP_SMTP_AUTH_ACCEPT_ANY=${MP_SMTP_AUTH_ACCEPT_ANY:-1}
      - MP_SMTP_AUTH_ALLOW_INSECURE=${MP_SMTP_AUTH_ALLOW_INSECURE:-1}
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    restart: unless-stopped
    networks:
      - willowcms_network

  redis-commander:
    image: rediscommander/redis-commander:${REDIS_COMMANDER_IMAGE_TAG:-latest}
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${REDIS_COMMANDER_HTTP_PORT:-8084}:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_COMMANDER_USERNAME:-admin}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
      - TZ=${APP_DEFAULT_TIMEZONE:-America/Chicago}
    restart: unless-stopped
    networks:
      - willowcms_network
    profiles:
      - debug

volumes:
  willowcms_mysql_data:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_mysql_data
  willowcms_mysql_logs:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_mysql_logs
  willowcms_mysql_config:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_mysql_config
  willowcms_redis_data:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_redis_data
  willowcms_mailpit_data:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_mailpit_data
  willowcms_mailpit_logs:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_mailpit_logs
  willowcms_production_app:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_app_data
  willowcms_production_logs:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_logs
  willowcms_production_nginx_logs:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_nginx_logs
  willowcms_production_storage:
    driver: ${VOLUME_DRIVER:-local}
    name: ${PROJECT_NAME:-willowcms}_production_storage

networks:
  willowcms_network:
    driver: bridge
    name: ${NETWORK_NAME:-willowcms_production_network}